"""Add internal notes

Revision ID: 41795171dc96
Revises: b70463f47b4e
Create Date: 2025-12-16 23:21:18.293150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41795171dc96'
down_revision = 'b70463f47b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('internal_notes')

    # ### end Alembic commands ###
